config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'

  devise_for :users, :controllers => {
    :omniauth_callbacks =>  "users/omniauth_callbacks"
  }

  resources :tops, only: [:top, :privacy]
  get 'tops/top', to: 'tops#top'
  get 'tops/privacy', to: 'tops#privacy'

  resources :users, only: [:show, :edit, :update, :destroy, :calendar]

  resources :books, { only: [:show, :create] } do
  	collection do
  		get :search
      get :detail
  	end
  end

  resources :bookshelves, only: [:create, :update, :destroy]

  resources :recommendeds, only: [:create, :destroy]

  resources :todolists, only: [:index, :edit, :create, :update, :destroy] do
    patch :congratulations
    collection do
      delete 'destroy_all'
    end
  end

  resources :records, only: [:index, :edit, :create, :update]

end

app/models/record.rb
class Record < ApplicationRecord
	belongs_to :user

	validates :user_id, :title, :body, :studytime, presence: true
	validates :title, length: { maximum: 20 }
	validates :body, length: { maximum: 92 }

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
	before_action :authenticate_user!
	before_action :twitter_client, only: [:create]

	def index
	  @records = current_user.records.order("id DESC").page(params[:page]).per(10)
	  @record = Record.new
	end

	def edit
	  @record = Record.find(params[:id])
	  if @record.user_id != current_user.id
      	redirect_to root_path
      end
	end

	def create
	  @record = Record.new(record_params)
      @record.user_id = current_user.id

      #本日2回連続投稿を禁止するif文
      if  current_user.records.blank? || current_user.records.last.created_at.strftime("%Y-%m-%d") != Date.today.strftime("%Y-%m-%d")
        if  @record.save
      	  totalstudytime = current_user.records.sum(:studytime)
          @record.until_today_studytime = totalstudytime
          @record.save
          flash[:add_record] = "本日の進捗を追加しました"
          #Twitter投稿用の記述
          @client.update("タイトル：#{@record.title}\n内容：#{@record.body}\n学習時間：#{@record.studytime} h\n総計：#{@record.until_today_studytime} h")
          render :newpost
        else
          flash[:miss_add_record] = "学習項目と期限を入力してください"
          render :message
        end
      #本日2回連続投稿の失敗処理を入れる
      else
      	flash[:miss_sameday_record] = "同じ日に学習記録があります"
        render :message
      end
	end

	def update
	  @record = current_user.records.find(params[:id])
	  if @record.update(record_params)
	  	allrecords =  current_user.records.all

	  	allrecords.each.with_index(0) do |re, e|
	      i = 0
	      until_total_studytime = 0
	  	  while i <= e
	  	  	until_total_studytime += allrecords[i].studytime
	  	  	i += 1
	  	  end
	  	  re.until_today_studytime = until_total_studytime
	  	  re.save
        end

	    flash[:success_record_update]  = "進捗内容を更新しました"
		redirect_to records_path
	  else
	  	flash[:miss_recored_update]  = "項目を埋めて下さい"
		render 'edit'
	  end
	end

	private

	def record_params
	  params.require(:record).permit(:title, :body, :studytime)
	end

	def twitter_client
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key = ENV['Twitter_API_KEY']
      config.consumer_secret = ENV['Twitter_API_secret_KEY']
      config.access_token = ENV['Twitter_Access_token']
      config.access_token_secret = ENV['Twitter_Access_token_secret']
    end
  end

end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_message.html.erb
<% if flash[:miss_add_record] %>
  <div class="remove">
    <div class="alert alert-danger">
      <%= flash[:miss_add_record] %>
    </div>
  </div>
<% end %>
<% if flash[:miss_sameday_record] %>
  <div class="remove">
    <div class="alert alert-warning">
      <%= flash[:miss_sameday_record] %>
    </div>
  </div>
<% end %>

app/views/records/_record.html.erb
<tr>
  <th>
    <h5>
      <%= link_to edit_record_path(record.id) do %>
        <%= record.created_at.strftime("%Y-%m-%d") %>
      <% end %>
    </h5>
  </th>
  <th>
    <h4><%= record.title %></h4>
  </th>
  <th>
    <h4><%= record.body %></h4>
  </th>
  <th>
    <h4><%= record.studytime %>時間</h4>
    <h4>(<%= record.until_today_studytime %>時間)</h4>
  </th>
  <th>
    <%= link_to "編集", edit_record_path(record.id), :class =>"btn btn-success" %>
  </th>
</tr>

app/views/records/_records.html.erb
<div class="row">
  <div class="col-lg-12">
      <div class="col-lg-8">
        <h3>成果報告一覧</h3><br>
      </div>
      <div class="col-lg-4">
        <% if flash[:add_record] %>
          <div class="remove">
            <div class="alert alert-success">
              <%= flash[:add_record] %>
            </div>
          </div>
        <% end %>
      </div>
      <table class="table table-striped" style="table-layout:fixed;width:100%;">
        <colgroup>
          <col style="width:10%;">
          <col style="width:15%;">
          <col style="width:55%;">
          <col style="width:10%;">
          <col style="width:10%;">
        </colgroup>
        <thead>
          <tr>
            <th>日付</th>
            <th>項目</th>
            <th>詳細</th>
            <th>学習時間<br>(合計学習時間)</th>
            <th>その他</th>
          </tr>
        </thead>
        <tbody id="record_newpost" style="word-wrap:break-word;">
          <% records.each do |record| %>
            <%= render partial: "record", locals: { record: record } %>
          <% end %>
        </tbody>
      </table>
    <div class="page_center">
      <%= paginate records %>
    </div>
  </div>
</div>

app/views/records/_studychart.html.erb
<% if @studychart.present? %>
  <div class="form-group">
    <%= form_with(url: user_path(current_user.id), method: :get, local: true, class: "form-inline") do |f| %>
      <%= f.select :study_term, [['期間別に表示', 0], ['１週間', 1], ['１ヶ月', 2], ['３ヶ月', 3], ['１年間', 4], ['全期間', 5]], { include_blank: true, selected: 0 }, {  class: "form-control" } %>
      <%= f.submit "期間を変更する", class: "btn btn-primary btn-mg" %>
    <% end %>
  </div>
  <p>時間(h)</p>
  <%= line_chart @studychart, xtitle: "日付" %>
<% else %>
  <h4>学習時間を記録しよう！</h4>
<% end %>

app/views/records/edit.html.erb
<div class="record-index contaiber">
  <div class="backimage">
    <div class="row">
      <div class="col-md-8">
        <h3>進捗の編集</h3>
        <%= form_with(model: @record, url: record_path(@record), local: true) do |r| %>
          <label class="new-record-title" for="">学習項目</label>
          <%= r.text_field :title, class: 'form-control' %>
          <label class="new-record-body" for="">進捗内容</label>
          <%= r.text_area :body, class: 'form-control', style: "height: 100px;" %>
          <label class="new-record-studytime sr-only" for="">学習時間</label><br>
          <div class="input-group">
            <span class="input-group-addon">学習時間：</span>
            <%= r.number_field :studytime, min: 0, max: 24, class: 'form-control', :step=>"0.1" %>
            <span class="input-group-addon">時間</span>
          </div>
          <div class="col-md-4">
            <div class="new-todo-create"><%= r.submit '変更を確定する', class: "btn btn-warning", style: "width: 150px;" %></div>
          </div>
          <div class="col-md-8">
            <br>
            <% if flash[:miss_recored_update] %>
              <div class="fadeout">
                <div class="alert alert-danger">
                  <%= flash[:miss_recored_update] %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/records/index.html.erb
<div class="record-index contaiber">
  <div class="row">
  	<div class="col-md-8">
  	  <h3>本日の進捗</h3>
      <%= form_with(model: @record, url: records_path) do |r| %>
        <label class="new-record-title" for="">学習項目</label>
        <%= r.text_field :title, class: 'form-control', placeholder: "学習報告はTwitterにも連動して投稿できます(20文字)" %>
        <label class="new-record-body" for="">進捗詳細</label>
        <%= r.text_area :body, class: 'form-control', style: "height: 100px;", placeholder: "学習報告はTwitterにも連動して投稿できます(90文字)"%>
        <label class="new-record-studytime sr-only" for="">学習時間</label><br><br>
        <div class="input-group">
          <span class="input-group-addon">学習時間：</span>
          <%= r.number_field :studytime, min: 0, max: 24, class: 'form-control', :step=>"0.1" %>
          <span class="input-group-addon">時間</span>
        </div>
        <div class="col-md-4">
          <div class="new-todo-create"><%= r.submit '学習内容を報告する', class: "btn btn-warning", style: "width: 150px;" %></div>
        </div>
      <% end %>
      <br>
      <div id="record_message_area" class="col-md-8">
        <%= render partial: "message" %>
      </div>
      <div class="col-md-8">
        <% if flash[:success_record_update] %>
          <div class="fadeout">
            <div class="alert alert-success">
              <%= flash[:success_record_update] %>
            </div>
          </div>
        <% end %>
        <% if flash[:miss_recored_update] %>
          <div class="fadeout">
            <div class="alert alert-danger">
              <%= flash[:miss_recored_update] %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div id="records_area">
      <%= render partial: "records", locals: { records: @records } %>
    </div>
  </div>
</div>

app/views/records/index.js.erb
$("#records_area").html("<%= j(render 'records', { records: @records }) %>")
$("textarea").val('')
$("input").val('')

$(function(){
  setTimeout("$('.remove').fadeOut('slow')", 3000)
})

app/views/records/message.js.erb
$("#record_message_area").html("<%= j(render 'message') %>")

$(function(){
	$(".remove").show()
  setTimeout("$('.remove').fadeOut('slow')", 3000)
})

app/views/records/newpost.js.erb
$("#record_newpost").prepend("<%= j(render 'record', { record: @record }) %>")
$("textarea").val('')
$("input").val('')

$(function(){
	$(".remove").show()
  setTimeout("$('.remove').fadeOut('slow')", 3000)
})

app/views/records/studychart.js.erb
$("#studychart_area").html("<%= j(render 'records/studychart', { studychart: @studychart }) %>")