config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'

  devise_for :users, :controllers => {
    :omniauth_callbacks =>  "users/omniauth_callbacks"
  }

  resources :tops, only: [:top, :privacy]
  get 'tops/top', to: 'tops#top'
  get 'tops/privacy', to: 'tops#privacy'

  resources :users, only: [:show, :edit, :update, :destroy, :calendar]

  resources :books, { only: [:show, :create] } do
  	collection do
  		get :search
      get :detail
  	end
  end

  resources :bookshelves, only: [:create, :update, :destroy]

  resources :recommendeds, only: [:create, :destroy]

  resources :todolists, only: [:index, :edit, :create, :update, :destroy] do
    patch :congratulations
    collection do
      delete 'destroy_all'
    end
  end

  resources :records, only: [:index, :edit, :create, :update]

end

app/models/recommended.rb
class Recommended < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates_uniqueness_of :book_id, scope: :user_id
	validates :user_id, :book_id, presence: true

end

app/controllers/recommendeds_controller.rb
class RecommendedsController < ApplicationController
	before_action :authenticate_user!

	def create
	  @read_books = current_user.bookshelves.where(status: 2)
	  recommend = Recommended.create(user_id: current_user.id, book_id: recommend_params[:book_id])
	  flash[:create_recommend] = "技術書「#{recommend.book.title}」をお勧めしました"
	  render 'recommendeds/index.js.erb'
	end

	def destroy
	  @read_books = current_user.bookshelves.where(status: 2)
	  recommend = current_user.recommendeds.find(params[:id])
      recommend.destroy
      flash[:destroy_recommend] = "「#{recommend.book.title}」のお勧めを解除しました"
      render 'recommendeds/index.js.erb'
	end

	private

	def recommend_params
	  params.permit(:book_id)
	end

end

app/helpers/recommendeds_helper.rb
module RecommendedsHelper
end

app/views/recommendeds/_recommendeds.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>学習済みの本</h4>
  </div>
  <div class="panel-body">
    <% read_books.each do |boo| %>
      <div class="col-sm-2">
        <div class="panel panel-default">
          <div class="panel-heading usershow-book">
            <%= link_to book_path(boo.book.id) do %>
              <img src="<%= boo.book.small_image_url %>" alt="本の表紙", :image, style: "width: 150px; height: 150px;", fallback: "no_image.png" >
            <% end %>
          </div>
          <ul class="usershow-book list-group">
            <% if current_user.already_recommended?(boo.book) %>
              <li class="recommend list-group-book">
                <%= link_to recommended_path(id: current_user.recommendeds.find_by(user_id: current_user.id, book_id: boo.book_id).id), method: :delete, remote: true do %>
                  <i class="glyphicon glyphicon-star" aria-hidden="true" style="color: gold;"></i>
                  <i>お勧め済み</i>
                <% end %>
              </li>
            <% else %>
              <li class="recommend list-group-book">
                <%= link_to recommendeds_path(book_id: boo.book_id), method: :post, remote: true do %>
                  <i class="glyphicon glyphicon-star-empty" aria-hidden="true"></i>
                  <i>お勧めする</i>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
  <% if flash[:create_recommend] %>
  <div class="remove">
    <div class="alert alert-success">
      <%= flash[:create_recommend] %>
    </div>
  </div>
<% end %>
<% if flash[:destroy_recommend] %>
  <div class="remove">
    <div class="alert alert-warning">
      <%= flash[:destroy_recommend] %>
    </div>
  </div>
<% end %>
</div>

app/views/recommendeds/index.js.erb
$("#recommendeds_area").html("<%= j(render 'recommendeds/recommendeds', { read_books: @read_books }) %>")

$(function(){
	$(".remove").show()
  setTimeout("$('.remove').fadeOut('slow')", 3000)
})