config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'

  devise_for :users, :controllers => {
    :omniauth_callbacks =>  "users/omniauth_callbacks"
  }

  resources :tops, only: [:top, :privacy]
  get 'tops/top', to: 'tops#top'
  get 'tops/privacy', to: 'tops#privacy'

  resources :users, only: [:show, :edit, :update, :destroy, :calendar]

  resources :books, { only: [:show, :create] } do
  	collection do
  		get :search
      get :detail
  	end
  end

  resources :bookshelves, only: [:create, :update, :destroy]

  resources :recommendeds, only: [:create, :destroy]

  resources :todolists, only: [:index, :edit, :create, :update, :destroy] do
    patch :congratulations
    collection do
      delete 'destroy_all'
    end
  end

  resources :records, only: [:index, :edit, :create, :update]

end

app/models/book.rb
class Book < ApplicationRecord
	has_many :recommendeds
	has_many :bookshelves
	has_many :users, { through: :bookshelves }
	has_many :recommended_users, through: :recommended, source: :user

	validates :title, :url, :book_code, :medium_image_url, presence: true

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def search
      @books = []
      @title = booktitle_params[:title]
      if @title.present?
          @books = search_items(@title)
      end
    end

  	def show
      @book = Book.find(params[:id])
  	end

  	def detail
  	  results = RakutenWebService::Books::Book.search({
        isbn: bookcode_params[:book_code]
      })
      @book = Book.new(read(results.first))
  	end

    private

    def booktitle_params
      params.permit(:title)
    end

    def bookcode_params
      params.permit(:book_code)
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books.html.erb
<% if @books.present? %>
  <div class="row">
    <% @books.each do |book| %>
      <div class="book">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <%=link_to detail_books_path(book_code: book.book_code) do %>
                <img src="<%= book.medium_image_url %>" alt="本の表紙" width="170px" height="230px">
              <% end %>
            </div>
            <div class= "bookshelf-buttom">
              <% if user_signed_in? %>
                <% unless current_user.havebook(book) %>
                    <%= form_with(url: bookshelves_path, local: true) do |f| %>
                      <%= f.hidden_field :book_code, value: book.book_code %>
                      <%= f.submit "本棚に加える", class:"btn btn-primary" %>
                    <% end %>
                <% else %>
                  <input type="button" onclick="location.href='<%= book.url %>'"value="楽天で確認する", class= "btn btn-danger">
                <% end %>
              <% else %>
                <input type="button" onclick="location.href='<%= book.url %>'"value="楽天で確認する", class= "btn btn-danger">
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/books/detail.html.erb
<% if flash[:success_getbook] %>
  <div class="alert alert-success">
    <%= flash[:success_getbook] %>
  </div>
<% end %>
<div class="container book-show">
  <div class="row">
    <div class="col-md-4">
      <img src="<%= @book.medium_image_url %>" alt="本の表紙"　width="300px" height="300px">
      <div class= "bookshelf-buttom_show">
        <% if user_signed_in? %>
          <% unless current_user.havebook(@book) %>
            <div class="book-btn">
              <%= form_with(url: bookshelves_path, local: true) do |f| %>
                <%= f.hidden_field :book_code, value: @book.book_code %>
                <%= f.submit "本棚に加える", class:"btn btn-primary", style: "width :220px;" %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-8">
      <ul class="list-group">
        <li class="book-title list-group-item">タイトル：<%= @book.title %></li>
        <li class="book-author list-group-item">著者：<%= @book.author %></li>
        <li class="book-price list-group-item">価格：<%= @book.price %>円(税込)</li>
        <li class="book-release list-group-item">発売日：<%= @book.sales_date %></li>
        <li class="book-description list-group-item">レビュー評価値：<%= @book.review_average %></li>
        <li class="book-description list-group-item">レビュー数：<%= @book.review_count %></li>
        <li class="book-description list-group-item"><%= @book.caption %></li>
      </ul>
      <div class= "bookshelf-buttom">
        <input type="button" onclick="location.href='<%= @book.url %>'"value="楽天で確認する", class= "btn btn-danger btn-block">
      </div>
    </div>
  </div>
</div>

app/views/books/search.html.erb
<% if flash[:danger] %>
  <div class="alert alert-danger">
    <%= flash[:danger] %>
  </div>
<% end %>
<% if flash[:success_getbook] %>
  <div class="alert alert-success">
    <%= flash[:success_getbook] %>
  </div>
<% end %>

<div class="container">
  <h3>技術書一覧</h3>
  <div class="search">
    <div class="row">
      <div class="text-center">
        <%= form_with(url: search_books_path, method: :get, local: true, class: "form-inline") do |f| %>
          <div class="form-group">
            <%= f.text_field :title, class: "form-control input-mg", placeholder: "技術書のキーワードを入力", size: 30 %>
          </div>
          <%= f.submit "技術書を検索", class: "btn btn-primary btn-mg" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="search_backimage">
  <%= render partial: "books", books: @books %>
</div>

app/views/books/show.html.erb
<div class="container book-show">
  <div class="row">
    <div class="col-lg-4">
      <img src="<%= @book.medium_image_url %>" alt="本の表紙"　width="300px" height="300px">
        <div class= "bookshelf-buttom_show">
        <% if user_signed_in? %>
          <% unless current_user.havebook(@book) %>
            <div class="book-btn">
              <%= form_with(url: bookshelves_path, local: true) do |f| %>
                <%= f.hidden_field :book_code, value: @book.book_code %>
                <%= f.submit "本棚に加える", class:"btn btn-primary", style: "width :220px;" %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-8">
      <ul class="list-group">
        <li class="book-title list-group-item">タイトル：<%= @book.title %></li>
        <li class="book-author list-group-item">著者：<%= @book.author %></li>
        <li class="book-price list-group-item">価格：<%= @book.price %>円(税込)</li>
        <li class="book-release list-group-item">発売日：<%= @book.sales_date %></li>
        <li class="book-description list-group-item">レビュー評価値：<%= @book.review_average %></li>
        <li class="book-description list-group-item">レビュー数：<%= @book.review_count %></li>
        <li class="book-description list-group-item"><%= @book.caption %></li>
      </ul>
      <div class= "bookshelf-buttom">
        <input type="button" onclick="location.href='<%= @book.url %>'"value="楽天で確認する", class= "btn btn-danger btn-block">
      </div>
    </div>
  </div>
</div>