config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'

  devise_for :users, :controllers => {
    :omniauth_callbacks =>  "users/omniauth_callbacks"
  }

  resources :tops, only: [:top, :privacy]
  get 'tops/top', to: 'tops#top'
  get 'tops/privacy', to: 'tops#privacy'

  resources :users, only: [:show, :edit, :update, :destroy, :calendar]

  resources :books, { only: [:show, :create] } do
  	collection do
  		get :search
      get :detail
  	end
  end

  resources :bookshelves, only: [:create, :update, :destroy]

  resources :recommendeds, only: [:create, :destroy]

  resources :todolists, only: [:index, :edit, :create, :update, :destroy] do
    patch :congratulations
    collection do
      delete 'destroy_all'
    end
  end

  resources :records, only: [:index, :edit, :create, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Study Engineering</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
    <header class="navbar-inverse" style="background-color:#00AA00;">
      <% if user_signed_in? %>
        <div class="container" style="font-family: HGP行書体;">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Study Engineering", user_path(current_user.id), id: "logo"%>
          </div>
          <nav>
            <ul id="navbar" class="nav navbar-nav navbar-right navbar-collapse collapse">
              <li><a href= "https://www.wantedly.com" alt="wantedlyアイコンにリンク"　><i class="icon-on"><%= fa_icon("wikipedia-w 2x") %></i></a></li>
              <li><a href= "https://github.co.jp/" alt="githubアイコンにリンク"　><i class="icon-on"><%= fa_icon("github 2x") %></i></a></li>
              <li><a href= "https://twitter.com" alt="Twitterアイコンにリンク"　><i class="icon-on"><%= fa_icon("twitter 2x") %></i></a></li>
              <li><%= link_to "ユーザー情報の編集", edit_user_path(current_user.id), class: "glyphicon under_bar", :style => "color:#fff;" %></li>
              <li><%= link_to "学習記録をつける", records_path, class: "glyphicon under_bar", :style => "color:#fff;" %></li>
              <li><%= link_to " TODOリストの追加", todolists_path, class: "glyphicon under_bar", :style => "color:#fff;" %></li>
              <li><%= link_to " 技術書の検索", search_books_path, class: "glyphicon glyphicon-book under_bar", :style => "color:#fff;" %></li>
              <li><%= link_to " ログアウト", destroy_user_session_path, method: :delete, class: "glyphicon under_bar", :style => "color:#fff;" %></li>
            </ul>
          </nav>
        </div>
      <% else %>
        <div class="container" style="font-family: HGP行書体;">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Study Engineering", root_path, id: "logo"%>
          </div>
          <nav>
            <ul id="navbar" class="nav navbar-nav navbar-right navbar-collapse collapse">
              <li><a href= "https://www.wantedly.com" alt="wantedlyアイコンにリンク"　><i class="icon-off"><%= fa_icon("wikipedia-w 2x") %></i></a></li>
              <li><a href= "https://github.co.jp/" alt="githubアイコンにリンク"　><i class="icon-off"><%= fa_icon("github 2x") %></i></a></li>
              <li><a href= "https://twitter.com" alt="Twitterアイコンにリンク"　><i class="icon-off"><%= fa_icon("twitter 2x") %></i></a></li>
              <li><%= link_to " 技術書の検索", search_books_path, class: "glyphicon under_bar", :style => "color:#fff;" %></li>
              <li><%= link_to " 新規登録", new_user_registration_path, class: "glyphicon under_bar", :style => "color:#fff;" %></li>
              <li><%= link_to " ログイン", new_user_session_path, class: "glyphicon under_bar", :style => "color:#fff;" %></li>
            </ul>
          </nav>
        </div>
      <% end %>
    </header>

    <%= yield %>

    <footer class="navbar-inverse" style="background-color:#00AA00;">
      <div class="container" style="font-family: HGP行書体;">
        <nav>
          <ul class="nav navbar-nav navbar-center">
            <li class="list-inline-item"><%= link_to "StudyEngieeringトップページ", root_path, class: "under_bar", :style => "color:#fff;" %></li>
            <li class="list-inline-item"><a style = "color:#fff;">|</a></li>
            <li class="list-inline-item"><%= link_to "プライバシーポリシー", tops_privacy_path, class: "under_bar", :style => "color:#fff;" %></li>
          </ul>
          <ul class="nav navbar-nav navbar-center">
            <li class="list-inline-item"><a style = "color:#fff; font-size: 12px;">© 2019 Copyright: Study Engieering</a></li>
          </ul>
        </nav>
      </div>
    </footer>

  </body>
</html>